apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.appName}}-app
  labels:
    app: {{.Values.appName}}-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{.Values.appName}}-app
  template:
    metadata:
      labels:
        app: {{.Values.appName}}-app
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name:  {{.Values.appName}}-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
