apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appName}}-service
  labels:
    app: {{.Values.appName}}
spec:
  type: nodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{.Values.appName}}
